api_platform:
    graphql:
        enabled: false
    title: Lavka Engine API
    version: 0.5.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
