# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Inventory\Domain\StockRepository:
        alias: App\Inventory\Infrastructure\Doctrine\DoctrineStockRepository
    App\Shared\Domain\RecordStore:
        alias: App\Shared\Infrastructure\Persistence\Records
    App\Pricing\Domain\PricingRepository:
        alias: App\Pricing\Infrastructure\PricingRepository
    App\Inventory\Domain\StockAdjuster:
        alias: App\Inventory\Infrastructure\Doctrine\StockAdjuster
